### ISSUE TITLE
安装后报错，无法加载插件，显示'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by DreamGallery** [ikarosf/nonebot_plugin_gakuenImasCalculator#2]
看了一下原因，安装后插件文件夹内没有那些用来识别的图片，cv读取会失败
![image](https://github.com/user-attachments/assets/bbda6d85-79d7-4ad9-8d26-ffbb1eb903e3)

**Comment by DreamGallery** [comment]
另外想问一下用图片识别但是遇到`sslv3 alert handshake failure`错误有办法解决吗
```
09-20 13:15:36 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_gakuenImasCalculator.calc, lineno=15) failed.
Traceback (most recent call last):
  File "/home/nonebot/miniconda3/envs/campus/lib/python3.12/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/home/nonebot/miniconda3/envs/campus/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/home/nonebot/miniconda3/envs/campus/lib/python3.12/site-packages/urllib3/connection.py", line 652, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "/home/nonebot/miniconda3/envs/campus/lib/python3.12/site-packages/urllib3/connection.py", line 805, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "/home/nonebot/miniconda3/envs/campus/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/home/nonebot/miniconda3/envs/campus/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/nonebot/miniconda3/envs/campus/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/nonebot/miniconda3/envs/campus/lib/python3.12/ssl.py", line 1042, in _create
    self.do_handshake()
  File "/home/nonebot/miniconda3/envs/campus/lib/python3.12/ssl.py", line 1320, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nonebot/miniconda3/envs/campus/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/home/nonebot/miniconda3/envs/campus/lib/python3.12/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nonebot/miniconda3/envs/campus/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/home/nonebot/miniconda3/envs/campus/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "/home/nonebot/miniconda3/envs/campus/lib/python3.12/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='multimedia.nt.qq.com.cn', port=443): Max retries exceeded with url: /download?appid=1406&fileid=CgoyNTExNDYyNTA4EhQfVzcAN61BTyouY_v7PhboAGHN_BjJ5Qkg_gooyvuciOLQiAMyBHByb2RQgLsv&spec=0&rkey=CAESKBkcro_MGujokCQEjS-KTYkIVJASmREiXxD3z7jj0Bs6IXK_pGbJH3s (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1000)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "/home/nonebot/miniconda3/envs/campus/lib/python3.12/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "/home/nonebot/miniconda3/envs/campus/lib/python3.12/site-packages/nonebot/drivers/fastapi.py", line 186, in run
    uvicorn.run(
  File "/home/nonebot/miniconda3/envs/campus/lib/python3.12/site-packages/uvicorn/main.py", line 577, in run
    server.run()
  File "/home/nonebot/miniconda3/envs/campus/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/nonebot/miniconda3/envs/campus/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
  File "/home/nonebot/miniconda3/envs/campus/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/home/nonebot/miniconda3/envs/campus/lib/python3.12/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
  File "/home/nonebot/miniconda3/envs/campus/lib/python3.12/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/home/nonebot/miniconda3/envs/campus/lib/python3.12/site-packages/nonebot/internal/matcher/matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/home/nonebot/miniconda3/envs/campus/lib/python3.12/site-packages/nonebot/internal/matcher/matcher.py", line 825, in simple_run
    await handler(
  File "/home/nonebot/miniconda3/envs/campus/lib/python3.12/site-packages/nonebot/dependencies/__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/home/nonebot/miniconda3/envs/campus/lib/python3.12/site-packages/nonebot_plugin_gakuenImasCalculator/calc.py", line 32, in _
    args = getattrs(segment.data["url"])
  File "/home/nonebot/miniconda3/envs/campus/lib/python3.12/site-packages/nonebot_plugin_gakuenImasCalculator/OCRattrs.py", line 26, in getattrs
    large_image = getpic(url)
  File "/home/nonebot/miniconda3/envs/campus/lib/python3.12/site-packages/nonebot_plugin_gakuenImasCalculator/downloadpic.py", line 15, in getpic
    response = requests.get((__pic_url))
  File "/home/nonebot/miniconda3/envs/campus/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/nonebot/miniconda3/envs/campus/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/nonebot/miniconda3/envs/campus/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/nonebot/miniconda3/envs/campus/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/nonebot/miniconda3/envs/campus/lib/python3.12/site-packages/requests/adapters.py", line 698, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='multimedia.nt.qq.com.cn', port=443): Max retries exceeded with url: /download?appid=1406&fileid=CgoyNTExNDYyNTA4EhQfVzcAN61BTyouY_v7PhboAGHN_BjJ5Qkg_gooyvuciOLQiAMyBHByb2RQgLsv&spec=0&rkey=CAESKBkcro_MGujokCQEjS-KTYkIVJASmREiXxD3z7jj0Bs6IXK_pGbJH3s (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1000)')))
```

**Comment by ikarosf** [comment]
谢谢反馈，没有图片是打包错误的问题，已重新上传。
ssl 错误应该是multimedia.nt.qq.com.cn这个域名的证书python不支持，所以无法下载QQ聊天图片，我已尝试禁用ssl验证可能有效。

**Comment by DreamGallery** [comment]
> 谢谢反馈，没有图片是打包错误的问题，已重新上传。 ssl 错误应该是multimedia.nt.qq.com.cn这个域名的证书python不支持，所以无法下载QQ聊天图片，我已尝试禁用ssl验证可能有效。

辛苦大佬了，不过你更新的禁用ssl验证的方法似乎只支持urllib3<2的版本，我本地的版本是2.2.2，会出现
```
ImportError: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_'
```
的错误，怕依赖可能会出现其他问题，暂时就不降级使用了
